import jsPDF from "jspdf";
import html2canvas from "html2canvas";

const esc = (s = "") =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

export const exportConversationPdf = async (title, messages) => {
  const safeTitle = (title || "ChatMaroc conversation").trim();
  const date = new Date().toLocaleString();

  const container = document.createElement("div");
  container.style.position = "fixed";
  container.style.left = "-10000px";
  container.style.top = "0";
  container.style.width = "720px";
  container.style.background = "#ffffff";
  container.style.color = "#0f172a";
  container.style.padding = "40px";
  container.style.fontFamily = "Figtree, Arial, sans-serif";
  container.style.fontSize = "15px";
  container.style.lineHeight = "1.6";

  const rows = messages
    .filter((m) => (m.content || "").trim())
    .map((m) => {
      const isUser = m.role === "user";
      const who = isUser ? "You" : "ChatMaroc";
      const color = isUser ? "#0e7490" : "#7c3aed";
      const bg = isUser ? "#ecfeff" : "#f5f3ff";
      const sources =
        m.sources && m.sources.length
          ? `<div style="margin-top:8px;font-size:12px;color:#475569;">Sources:<br/>${m.sources
              .map((s, i) => `${i + 1}. ${esc(s.title || s.url)} — ${esc(s.url)}`)
              .join("<br/>")}</div>`
          : "";
      return `
        <div style="margin-bottom:18px;padding:14px 16px;border-radius:14px;background:${bg};border:1px solid #e2e8f0;">
          <div style="font-weight:700;color:${color};margin-bottom:6px;font-size:13px;">${who}</div>
          <div dir="auto" style="white-space:pre-wrap;word-break:break-word;">${esc(m.content)}</div>
          ${sources}
        </div>`;
    })
    .join("");

  container.innerHTML = `
    <div style="display:flex;align-items:center;gap:10px;border-bottom:2px solid #06b6d4;padding-bottom:16px;margin-bottom:24px;">
      <div style="width:36px;height:36px;border-radius:10px;background:#0f172a;display:flex;align-items:center;justify-content:center;color:#67e8f9;font-weight:700;">CM</div>
      <div>
        <div style="font-size:22px;font-weight:700;font-family:Outfit,Figtree,sans-serif;">ChatMaroc</div>
        <div style="font-size:12px;color:#64748b;">${esc(safeTitle)} · Exported ${esc(date)}</div>
      </div>
    </div>
    ${rows || '<div style="color:#64748b;">No messages.</div>'}
    <div style="margin-top:28px;border-top:1px solid #e2e8f0;padding-top:12px;font-size:11px;color:#94a3b8;text-align:center;">
      Generated by ChatMaroc — Darija · Tamazight AI 🇲🇦
    </div>`;

  document.body.appendChild(container);
  try {
    const canvas = await html2canvas(container, { scale: 2, backgroundColor: "#ffffff", useCORS: true });
    const imgData = canvas.toDataURL("image/jpeg", 0.92);
    const pdf = new jsPDF("p", "mm", "a4");
    const pageW = pdf.internal.pageSize.getWidth();
    const pageH = pdf.internal.pageSize.getHeight();
    const imgW = pageW;
    const imgH = (canvas.height * imgW) / canvas.width;
    let heightLeft = imgH;
    let position = 0;
    pdf.addImage(imgData, "JPEG", 0, position, imgW, imgH);
    heightLeft -= pageH;
    while (heightLeft > 0) {
      position -= pageH;
      pdf.addPage();
      pdf.addImage(imgData, "JPEG", 0, position, imgW, imgH);
      heightLeft -= pageH;
    }
    const fname = `ChatMaroc-${(safeTitle.replace(/[^\w\u0600-\u06FF\u2D30-\u2D7F-]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 40)) || "chat"}.pdf`;
    pdf.save(fname);
  } finally {
    document.body.removeChild(container);
  }
};
